# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-locked:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v1
    - name: Install dependencies (locked)
      run: |
        uv venv
        uv pip install --upgrade pip
        uv pip install flake8 pytest
        uv pip install -e .
    - name: Lint with flake8
      run: |
        flake8 llm_recorder --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 llm_recorder --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  test-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v1
    - name: Install dependencies (latest compatible)
      run: |
        rm uv.lock  # Remove lockfile to force latest compatible versions
        uv venv
        uv pip install --upgrade pip
        uv pip install flake8 pytest
        uv pip install -e .
    - name: Lint with flake8
      run: |
        flake8 llm_recorder --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 llm_recorder --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
